from .powerlimit_node import SetPowerLimitNode, NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

# Expose node mappings to ComfyUI
NODE_CLASS_MAPPINGS = NODE_CLASS_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = NODE_DISPLAY_NAME_MAPPINGS